name: xmltovtt
description: A Dart console app, to convert subtitle files from xml to vtt.
version: 1.0.3
repository: https://github.com/belachkar/xmltovtt
issue_tracker: https://github.com/belachkar/xmltovtt/issues

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  args: ^2.4.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  xmltovtt: xmltovtt
